desktop view for pr review
supreeti/PortfolioMobileFirst pull request #10
Opened 2023-01-21 20:50 UTC by supreeti

Add html and Css file for desktop view.

2023-01-21 21:28 UTC, bienvenuushindi requested changes
## Hi @bienvenuushindi,

Good job so far!

## Highlights!
- GitFlow ✔️ 
- No linter errors ✔️ 
- Descriptive pull request ✔️ 


Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️

- [ ]  Please for future review Kindly make sure you keep the same pull request, (in this case it is #9 ) until it gets approved. when requesting for a re-review don't open a  new pull request use the previous one 

_Check the comments under the review and here 👇._


## Optional suggestions
- [ ] Kindly consider the optional comment left by the previous reviewer.
_Check the comments under the review and here 👇._
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-21 21:28 UTC, bienvenuushindi commented on index.css
:red_circle: [OPTIONAL] Please make sure your desktop version doesn't affect the mobile version of your portfolio. As for now, the mobile version has been affected immensely. Kindly fix this to have a professional portfolio. I think the big issue is with your about section The language, and skills framework section should move beneath the about block on the mobile version.

![Peek 2023-01-21 23-17](https://user-images.githubusercontent.com/26736582/213887487-26d72dce-972e-4a54-ac11-6bfd17a0dbc5.gif)

2023-01-21 21:28 UTC, bienvenuushindi commented on index.css
> +    padding-right: 90px;
:red_circle: [REQUESTED] As requested by the previous reviewer, Kindly make sure you fix the style of this paragraph to match the Figma Design. I think you can use pixels or rem for the font-size property to fix this

Your Design
![Screenshot from 2023-01-21 23-20-02](https://user-images.githubusercontent.com/26736582/213887682-f8f02654-63f6-4bc1-b27e-de8c6482f431.png)


Figma Design
![Screenshot from 2023-01-21 23-19-45](https://user-images.githubusercontent.com/26736582/213887684-9e2c7e99-9368-464e-9943-300481f21a34.png)

2023-01-28 13:18 UTC, ichala approved these changes
Hi Student  ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
 
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# To Highlight 💪🏻

- Changes Implemented ✔️ 


 Good job implementing the requirements  :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Optional Suggestions  :

- N/A


**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-28 15:37 UTC, merged