Mobilefirst pull request
supreeti/PortfolioMobileFirst pull request #2
Opened 2023-01-13 19:28 UTC by supreeti

Add portfolio pages in mobile view. Make changes in html and css file accordingly.Add more images.

2023-01-13 20:27 UTC, binhussen requested changes
Hi @supreeti , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media0.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights

- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-13 20:27 UTC, binhussen commented on index.html
> +                  </ul>
- Kindly, be sure that the bullet icons are visible 👍👌 and it is best to use style instead of image to display bullets👌👍

2023-01-13 20:27 UTC, binhussen commented on index.html
> +                    <li class="texttitle font3">2015</li>
- Kindly, be sure that the bullet icons are visible 👍👌 and it is best to use style instead of image to display bullets👌👍

2023-01-13 20:27 UTC, binhussen commented on index.html
> +                    <li class="texttitle font3">2015</li>
- Kindly, be sure that the bullet icons are visible 👍👌 and it is best to use style instead of image to display bullets👌👍

2023-01-13 20:27 UTC, binhussen commented on index.html
> +                    <li class="texttitle font3">2015</li>
- Kindly, be sure that the bullet icons are visible 👍👌 and it is best to use style instead of image to display bullets👌👍

2023-01-13 20:27 UTC, binhussen commented on index.html
> +                  <ul>
-Kindly, Your cards are not merged well as the Figma design, please give it a margin-left .👍👌


| Your design                                                             | Figma design                                         |
| --------------------------------------------------------------------------------| --------------------------------------------------------- |
|<img src="https://user-images.githubusercontent.com/52010789/212412245-4bc1bfe1-0321-4c50-9016-e2557306af82.png" width="200">|<img src="https://user-images.githubusercontent.com/52010789/212412240-8046f325-a922-4d12-9d0c-00b1b30f1d08.png" width="200">|


😎️

🤝️

2023-01-13 20:27 UTC, binhussen commented on index.html
> +              <h5>LET'S CONNECT</h5>
- Kindly, uses the font defined for the template and stick as much as posible with font weight, style....👌👍

2023-01-14 11:10 UTC, algerina approved these changes
Hi @supreeti ,
Good job so far! 

May I highlight the following:

- The repo looks professional.:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- Your project looks awesome:heavy_check_mark:

## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:
You did great implementing the previews TSE's requirements :+1: 
Your project is complete!  It's time to merge it :shipit:

<img src="https://media2.giphy.com/media/artj92V8o75VPL7AeQ/giphy.gif"/>

 
 ## Optional suggestions
 
 - Please check the comment under the review.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread and tag me @algerina if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [Algerina](https://github.com/algerina), I will receive a notification and will respond._

[GitHub](https://github.com/algerina) | [LinkedIn](https://linkedin.com/in/amel-khiri) | [Twitter](https://twitter.com/AmelQahwadji)

_Reviewed by [Amel Khiri ](https://github.com/algerina)_

2023-01-14 11:20 UTC, supreeti commented
Mobile First project completed

2023-01-14 11:20 UTC, merged